### ISSUE TITLE
Robbing Blank Tile

### ISSUE THREAD

**Issue by benjaminhafen** [rysav/cs340spring2016#10]
Moving the robber to a space with no players causes you to be prompted to rob players far away from the target space, if the robber was moved by playing soldier card, play continues as if nothing happened, player keeps card and robber returns to previous space, if it was placed because a rolled 7, it is followed by the game freezing (the game can be unfrozen by sending a chat message to force an update).

**Comment by rachel-trainor** [comment]
I had this issue as well but with a valid hex, I was set in robbing mode infinitely. Thought this should be mentioned, but not worth setting up a new issue as these are probably related :) 

![robberbug](https://cloud.githubusercontent.com/assets/16596996/15416349/931e47fe-1e07-11e6-91eb-fc77f2e43d3c.PNG)

**Comment by jbonner6** [comment]
All fixed. Thanks for the thorough findings!
