### ISSUE TITLE
Joining a new game freezes it.

### ISSUE THREAD

**Issue by razzleband** [rysav/cs340spring2016#39]
This bug seems to pop up every once in a while. Try replicating it several times.

To replicate, start the client and login as Sam. Make a new game. Once created, join that game. After setting AIs, the client gets stuck at the setup phase. 

here is the printout on the terminal when this occurs
![image](https://cloud.githubusercontent.com/assets/13368924/15436160/b05c5df8-1e7d-11e6-8a7b-935c4277bcd2.png)

As an example, here are some screenshots.
![image](https://cloud.githubusercontent.com/assets/13368924/15436178/c23a24ba-1e7d-11e6-8125-8afa37d7ec81.png)
Log in as Sam
![image](https://cloud.githubusercontent.com/assets/13368924/15436202/d834e7dc-1e7d-11e6-8cf8-fc8e97d0f760.png)
create a new game
![image](https://cloud.githubusercontent.com/assets/13368924/15436211/eb2619b0-1e7d-11e6-8728-073b615fbe12.png)
The game now shows up. Join it
![image](https://cloud.githubusercontent.com/assets/13368924/15436222/02b8dd92-1e7e-11e6-9a97-52766e244fee.png)
Select colors and add AIs
![image](https://cloud.githubusercontent.com/assets/13368924/15436427/14e8d2d2-1e7f-11e6-8a29-ae40d5e751b1.png)
It then freezes like this

**Comment by benjaminhafen** [comment]
This was accidentally labeled as both P2 and P3; it should only be P3, so I removed the extraneous label.

**Comment by caseymh** [comment]
Fixed the exceptions we were throwing. We have found that sometimes it freezes but it is when there is an exception in the server, not our client

**Comment by jangusbeef** [comment]
Server's exception reads as follows:
     [java] java.io.IOException: An existing connection was forcibly closed by the remote host
     [java]     at sun.nio.ch.SocketDispatcher.read0(Native Method)
     [java]     at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
     [java]     at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
     [java]     at sun.nio.ch.IOUtil.read(IOUtil.java:197)
     [java]     at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:379)
     [java]     at sun.net.httpserver.Request$ReadStream.read(Request.java:288)
     [java]     at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
     [java]     at java.io.BufferedInputStream.read(BufferedInputStream.java:254)
     [java]     at sun.net.httpserver.Request.readLine(Request.java:84)
     [java]     at sun.net.httpserver.Request.<init>(Request.java:54)
     [java]     at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:538)
     [java]     at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
     [java]     at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:433)
     [java]     at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:398)
     [java]     at java.lang.Thread.run(Thread.java:745)
