### ISSUE TITLE
Two Players Can Choose The Same Color

### ISSUE THREAD

**Issue by jangusbeef** [rysav/cs340spring2016#52]
If two clients connect to the server before either join a game, they can both select the same color. Potentially, you could have four green players which although does not interfere with actual game-play, it is super confusing and potentially the source of many headaches.

**Comment by benjaminhafen** [comment]
This is the behavior in the default example client, meaning that although it IS likely a bug, it is how the game client is expected to behave and cannot reasonably be fixed given the game design model. (We reported a similar bug ourselves but closed it after realizing this.See #13.) Marking as invalid.
