### ISSUE TITLE
Incorrect Trading

### ISSUE THREAD

**Issue by jangusbeef** [rysav/cs340spring2016#55]
Domestic Trade between 2 clients Does not function properly. Sometimes, when selecting a resource to send and receive, they will occasionally switch sides or all go to one side (send/receive). This results in incapability to trade properly, and possibly negative resources for the player starting the trade (receive becomes send and the trade is accepted)

Reproducible Example:
-press brick to receive 1
-press sheep to receive 1
-select other client player
-switch brick to send
-send request and witness

**Comment by tlyon3** [comment]
It's a feature! We want you to be able to give away resources and ask for them for free

**Comment by jangusbeef** [comment]
That's not the issue here though. The problem is that the request on one end is not the same as what is received on the other!

**Comment by tlyon3** [comment]
Ok we fixed it. Thanks for letting us now
