### ISSUE TITLE
Views don't always close when they should

### ISSUE THREAD

**Issue by cwpitts** [rysav/cs340spring2016#62]
It's pretty nondeterministic, but the views don't always close at the right time. Maybe check the conditions for closing them.

**Comment by benjaminhafen** [comment]
Could you give specific examples? Thanks!

**Comment by benjaminhafen** [comment]
As we have no specific examples to investigate and haven't encountered this issue, we'll go ahead and close this issue. If anyone runs into this specific bug again, comment and we will re-open it to investigate. Thanks!
