### ISSUE TITLE
 Accounting fraud: trading does not enforce constraints

### ISSUE THREAD

**Issue by cwpitts** [rysav/cs340spring2016#64]
Domestic trade can be offered without sending anything
Domestic trade can be offered without receiving anything
Maritime trade can be the same resource (i.e. trade four sheep for one sheep)

**Comment by benjaminhafen** [comment]
We consider these all to be within the rules of the game. Giving or receiving free resources is part of playing strategy (for example, to avoid going over 7 cards.) Maritime trades can be for any resource - trading for the same resource might not be a wise decision, but it is allowed within game rules. Marking as invalid.
