### ISSUE TITLE
Forced Road Building

### ISSUE THREAD

**Issue by jangusbeef** [rysav/cs340spring2016#81]
Close the application after building your first road and settlement. After re-joining the game, you will plave your second road and settlement, roll, then be forced to build a road. If you started w/ the resources necessary, you'll be able to place and continue. If not, the game can no longer be played!

**Comment by benjaminhafen** [comment]
Looks like this might be related to #77.

**Comment by tlyon3** [comment]
just leaving a note: this one might have been fixed. Need to try and replicate it a few more times to be sure.

**Comment by benjaminhafen** [comment]
It looks like this has been fixed; I tried several times to cause the issue and it no longer occurs.
