### ISSUE TITLE
Freezing

### ISSUE THREAD

**Issue by MasqueradeOfSilence** [rysav/cs340spring2016#87]
More serious issue: The game will sometimes freeze. It usually happens a few (2-3) rounds into gameplay. I will try and click on Chat Messages, End Turn, or Maritime/Domestic trade, and the game will freeze completely. Since it's stuck on that one player's turn, nobody else can do anything. The gameplay works very well up until this point. I tried waiting for a few minutes, but it didn't unfreeze. Not sure what may be causing this.

**Comment by benjaminhafen** [comment]
This looks like an effect resulting from #76. It's definitely an issue that we'll look into; we'll close this ticket since it's a duplicate, but keep an eye on #76 for updates on fixes. Thanks!
